EVT_PRINT_ERROR = 0
EVT_CONNECTION_ERROR = 1

SERVER_RESPONSE_UPLOAD_FAILURE = b'0'
SERVER_RESPONSE_UPLOAD_SUCCESS = b'1'
SERVER_RESPONSE_QUERY_FAILURE = b'2'
SERVER_RESPONSE_QUERY_SUCCESS = b'3'

EVT_SUBMIT_STARTED = 0
EVT_SUBMIT_SUCCESS = 1
EVT_SUBMIT_FAILURE = 2


EVT_SEARCH_STARTED = 0
EVT_SEARCH_SUCCESS = 1
EVT_SEARCH_FAILURE = 2
EVT_CLOSE_OUTPUT_PAGE = 3
EVT_TERMINATE_THREAD = 4


REQUEST_TYPE_UPLOAD = '0'
REQUEST_TYPE_QUERY = '1'

COLLECTION_SAMPLE = u'kwic_collection'
DOCUMENT_QUERY_URLS = u'kwic_query_document'
ARG_KWIC_KEYWORD_DATA = u'kwicKeywordData'
ARG_URL_ORIGINAL_KEYWORDS = u'urlOriginalKeywords'
ARG_URL = u'url'
ARG_NOISE_WORDS = u'noiseWords'
ARG_KEYWORDS = u'keywords'

DATABASE_URL = 'https://database-manager-dot-kwic-project.uc.r.appspot.com'
KWIC_WEBSERVER_URl = 'https://kwic-webserver-dot-kwic-project.uc.r.appspot.com'


GET_ARG_ORIGINAL_URL_KEYWORDS = 'originalUrlKeywords'
GET_ARG_KWIC_URL_KEYWORDS = 'kwicUrlKeywords'
GET_ARG_NOISE_WORDS = 'noiseWords'
GET_ARG_REQUEST_TYPE = 'requestType'
GET_ARG_KEYWORDS = 'keywords'